# Change these first
owner: EvanLuo233 # Your GitHub organization or username, where this repository lives
repo: AnonymousLandStatus # The name of this repository

sites:
  - name: Anonymous Land 主站
    url: https://www.evanluo.top
  - name: Alexwei的部落格
    url: http://alexwei.top

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.evanluo.top
  # baseUrl: /your-repo-name
  logoUrl: https://s4.ax1x.com/2022/02/14/HcCpaF.png
  name: Status
  introTitle: "**Evan's Websites** and friends' Websites Status"
  introMessage: By Evan Luo
  navbar:
    - title: Status
      href: /
    - title: HomePage
      href: https://www.evanluo.top

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
